import { NextResponse } from 'next/server'
import { searchMasterInput, updateOperation, getCashFlowByOperation, updateCashFlowTransaction, getAllContactos, getAllProductos } from '@/lib/googleSheets'
import { generateProformaData, OperationInput } from '@/lib/proformaEngine'
import { createInvoiceDoc, shareFile } from '@/lib/googleDocs'

// id:qty:price\nid:qty:price format
function serializeProducts(items: { id: string; qty: number; price: number }[]) {
    return items.map(i => `${i.id}:${i.qty}:${i.price}`).join('\n')
}

function numberToWords(num: number): string {
    const intPart = Math.floor(num)
    const cents = Math.round((num - intPart) * 100)
    const ones = ['', 'ONE', 'TWO', 'THREE', 'FOUR', 'FIVE', 'SIX', 'SEVEN', 'EIGHT', 'NINE',
        'TEN', 'ELEVEN', 'TWELVE', 'THIRTEEN', 'FOURTEEN', 'FIFTEEN', 'SIXTEEN', 'SEVENTEEN', 'EIGHTEEN', 'NINETEEN']
    const tens = ['', '', 'TWENTY', 'THIRTY', 'FORTY', 'FIFTY', 'SIXTY', 'SEVENTY', 'EIGHTY', 'NINETY']
    function below1000(n: number): string {
        if (n === 0) return ''
        if (n < 20) return ones[n] + ' '
        if (n < 100) return tens[Math.floor(n / 10)] + (n % 10 ? ' ' + ones[n % 10] : '') + ' '
        return ones[Math.floor(n / 100)] + ' HUNDRED ' + below1000(n % 100)
    }
    function convert(n: number): string {
        if (n === 0) return 'ZERO'
        let result = ''
        if (n >= 1000000) { result += below1000(Math.floor(n / 1000000)) + 'MILLION '; n %= 1000000 }
        if (n >= 1000) { result += below1000(Math.floor(n / 1000)) + 'THOUSAND '; n %= 1000 }
        result += below1000(n)
        return result.trim()
    }
    const words = convert(intPart)
    return `SAY TOTAL VALUE: ${words} DOLLARS AND ${cents.toString().padStart(2, '0')}/100 USD`
}

export async function POST(request: Request) {
    try {
        const body = await request.json()
        const { operationId, realProducts, invoiceNotes } = body
        // realProducts: Array<{ id: string; qty: number; salePrice: number; purchasePrice: number }>

        if (!operationId || !realProducts?.length) {
            return NextResponse.json({ success: false, error: 'operationId and realProducts required' }, { status: 400 })
        }

        // 1. Fetch operation
        const ops = await searchMasterInput(operationId)
        const op = ops.find(o => o.id === operationId)
        if (!op) return NextResponse.json({ success: false, error: 'Operation not found' }, { status: 404 })

        const [contacts, catalogProducts, allOps] = await Promise.all([
            getAllContactos(),
            getAllProductos(),
            searchMasterInput('')   // to calculate consecutive invoice number
        ])

        // ── Invoice Number ────────────────────────────────────────────────────
        // Format: {prefix}{consecutive}/{opId}  e.g. SW13/081-26
        // Base offsets = invoices done manually before this system existed
        const BASE_OFFSET: Record<string, number> = { SW: 12, SM: 17 }
        const tradingLower = (op.trading || '').toLowerCase()
        const prefix = tradingLower.includes('seawind') ? 'SW'
            : tradingLower.includes('sm') ? 'SM'
                : 'SW'  // default
        // Count invoices already generated by this system for this prefix
        const existingForPrefix = allOps.filter(o =>
            o.invoiceNumber && o.invoiceNumber.startsWith(prefix)
        ).length
        const consecutive = existingForPrefix + (BASE_OFFSET[prefix] ?? 0) + 1
        const invoiceNumber = `${prefix}${consecutive}/${op.id}`
        // ─────────────────────────────────────────────────────────────────────

        // 2. Build proforma-style data but with real quantities
        const input: OperationInput = {
            id_carga: op.id,
            user_id: op.userId || '',
            import_id: op.cliente,
            export_id: op.exportador,
            producer_id: op.productor || '',
            port_dest: op.puertoDestino || '',
            port_load: op.portLoad || 'Montevideo',
            incoterm: op.incoterm || 'CFR',
            ship_date: op.fechaEmbarque || new Date().toISOString(),
            ship_lane: op.shipLane || '',
            payment_terms: op.paymentTerms || '',
            trading: op.trading || '',
            notes: invoiceNotes || op.notas || '',
            notasProforma: invoiceNotes || op.notasProforma || '',
            brand: op.brand || '',
            products: realProducts.map((p: any) => ({ id: p.id, qty: p.qty, price: p.salePrice }))
        }

        const importers = contacts.filter(c => c.isImporter || c.tipo === 'Importador')
        const exporters = contacts.filter(c => c.isExporter || c.tipo === 'Exportador')
        const producers = contacts.filter(c => c.isProducer || c.tipo === 'Productor')

        const generatedData = generateProformaData(input, [], catalogProducts, importers, exporters, producers)

        // Patch replacements: use invoice_n (not proforma_n) + notes from form
        // invoiceNumber is already computed above (e.g. SW40/081-26)
        const realTotal = realProducts.reduce((s: number, p: any) => s + p.qty * p.salePrice, 0)
        const totalText = numberToWords(realTotal)

        const replacements = {
            ...generatedData.replacements,
            invoice_n: invoiceNumber,     // <<< Original Invoice placeholder
            proforma_n: invoiceNumber,    // fallback if template uses proforma_n
            notes: invoiceNotes || '',
            total_number: realTotal.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 }),
            total_text: totalText,
            date: new Date().toLocaleDateString('en-GB')
        }

        // Use descriptions from generatedData.products (built by proformaEngine with full
        // species + cut + calibre + packing + sci name + HS code logic) — same as Proforma
        const productsArray = realProducts.map((p: any, idx: number) => {
            const engineProduct = generatedData.products[idx]
            // Full description from engine (e.g. "Whiting HGT 200-300g - Interleaved\n(Sci: Merluccius hubbsi ...)")
            const desc = engineProduct?.description || p.id
            const saleSub = (p.qty * p.salePrice).toFixed(2)
            return {
                qty: String(p.qty),
                ctns: engineProduct?.cartons || String(p.qty),
                desc,
                unit: `$${Number(p.salePrice).toFixed(2)}`,
                subtotal: `$${saleSub}`
            }
        })

        // 3. Create document
        const folderId = op.idCarpeta || undefined
        const docName = `Original Invoice ${invoiceNumber} - ${op.cliente || ''}`
        const docId = await createInvoiceDoc(replacements, docName, folderId, productsArray)

        if (op.userId) await shareFile(docId, op.userId, 'writer')

        // 4. Update operation — save to new invoice-specific fields (do NOT overwrite productos/purchasePricesRaw)
        const realSaleRaw = serializeProducts(realProducts.map((p: any) => ({ id: p.id, qty: p.qty, price: p.salePrice })))
        const realPurchaseRaw = serializeProducts(realProducts.map((p: any) => ({ id: p.id, qty: p.qty, price: p.purchasePrice })))

        const estimatedTotal = (op.productos || '').split('\n').filter(Boolean).reduce((s, line) => {
            const parts = line.split(':')
            return s + (parseFloat(parts[1]) || 0) * (parseFloat(parts[2]) || 0)
        }, 0)
        const delta = realTotal - estimatedTotal

        await updateOperation(op.id!, {
            invoiceDocId: docId,
            invoiceNumber: invoiceNumber,   // e.g. SW40/081-26 → saved to 'Original Invoice Number' column
            invoiceNotes: invoiceNotes || '',
            salePriceReal: realSaleRaw,
            purchasePricesReal: realPurchaseRaw
        } as any)

        // 5. Adjust CashFlow balance if there's an advance payment
        if (Math.abs(delta) > 0.01) {
            try {
                const txs = await getCashFlowByOperation(operationId)
                // Find the non-advance sale transaction (the pending balance)
                const balanceTx = txs.find(tx =>
                    tx.status === 'PENDIENTE' &&
                    (tx.category?.toLowerCase().includes('saldo') ||
                        tx.category?.toLowerCase().includes('balance') ||
                        tx.category?.toLowerCase().includes('venta') ||
                        tx.category?.toLowerCase().includes('cobro'))
                )
                if (balanceTx && balanceTx.id) {
                    const newAmount = (balanceTx.amount || 0) + delta
                    await updateCashFlowTransaction(balanceTx.id, { amount: newAmount })
                    console.log(`[Invoice] Adjusted balance tx ${balanceTx.id} by ${delta} → ${newAmount}`)
                }
            } catch (cfErr) {
                console.error('[Invoice] CashFlow adjustment failed (non-critical):', cfErr)
            }
        }

        return NextResponse.json({
            success: true,
            docId,
            docUrl: `https://docs.google.com/document/d/${docId}/edit`,
            realTotal,
            estimatedTotal,
            delta
        })

    } catch (error: any) {
        console.error('Error generating original invoice:', error)
        return NextResponse.json({ success: false, error: error.message }, { status: 500 })
    }
}
